version: '2'
volumes:
  peer0.machine1.teco.com: {}
  peer1.machine1.teco.com: {}
networks:
  basic: {}
services:
  couchdb2:
    container_name: couchdb2
    image: 'vizlore/fabric-couchdb:latest'
    restart: always
    ports:
      - '7984:5984'
    environment:
      - GODEBUG=netdns=go
      - 'DB_URL:http://localhost:7984/member_db'
    networks:
      - basic
  peer0.machine1.teco.com:
    container_name: peer0.machine1.teco.com
    image: 'vizlore/fabric-peer:latest'
    logging:
      options:
        max-size: 10m
    restart: always
    environment:
      - GODEBUG=netdns=go
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - 'CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4'
      - 'CORE_PEER_CHAINCODEADDRESS=peer0.machine1.teco.com:7052'
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_PEER_ID=peer0.machine1.teco.com
      - 'CORE_PEER_ADDRESS=peer0.machine1.teco.com:7051'
      - 'CORE_PEER_LISTENADDRESS=0.0.0.0:7051'
      - 'CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052'
      - CORE_PEER_LOCALMSPID=suppMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - 'CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984'
      - 'CORE_PEER_GOSSIP_BOOTSTRAP=peer0.machine1.teco.com:7051'
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.machine1.teco.com:7051'
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - 'CORE_OPERATIONS_LISTENADDRESS=peer0.machine1.teco.com:8125'
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - '7051:7051'
      - '7053:7053'
      - '7052:7052'
      - '8125:8125'
    volumes:
      - '/var/run/:/host/var/run/'
      - './:/etc/hyperledger/configtx'
      - >-
        ./artifacts/channel/crypto-config/peerOrganizations/teco.com/peers/peer0.machine1.teco.com/msp:/etc/hyperledger/fabric/msp
      - >-
        ./artifacts/channel/crypto-config/peerOrganizations/teco.com/peers/peer0.machine1.teco.com/tls:/etc/hyperledger/fabric/tls
      - >-
        ./artifacts/channel/crypto-config/peerOrganizations/teco.com/users:/etc/hyperledger/msp/users
      - 'peer0.machine1.teco.com:/var/hyperledger/production'
    depends_on:
      - couchdb2
    networks:
      - basic
  peer1.machine1.teco.com:
    container_name: peer1.machine1.teco.com
    image: 'vizlore/fabric-peer:latest'
    logging:
      options:
        max-size: 10m
    restart: always
    environment:
      - GODEBUG=netdns=go
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - 'CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4'
      - 'CORE_PEER_CHAINCODEADDRESS=peer1.machine1.teco.com:8052'
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_PEER_ID=peer1.machine1.teco.com
      - 'CORE_PEER_ADDRESS=peer1.machine1.teco.com:7051'
      - 'CORE_PEER_LISTENADDRESS=0.0.0.0:7051'
      - 'CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052'
      - CORE_PEER_LOCALMSPID=suppMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - 'CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984'
      - 'CORE_PEER_GOSSIP_BOOTSTRAP=peer0.machine1.teco.com:7051'
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.machine1.teco.com:8051'
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - 'CORE_OPERATIONS_LISTENADDRESS=peer1.machine1.teco.com:8125'
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - '8051:7051'
      - '8053:7053'
      - '8052:8052'
      - '9125:8125'
    volumes:
      - '/var/run/:/host/var/run/'
      - './:/etc/hyperledger/configtx'
      - >-
        ./artifacts/channel/crypto-config/peerOrganizations/teco.com/peers/peer1.machine1.teco.com/msp:/etc/hyperledger/fabric/msp
      - >-
        ./artifacts/channel/crypto-config/peerOrganizations/teco.com/peers/peer1.machine1.teco.com/tls:/etc/hyperledger/fabric/tls
      - >-
        ./artifacts/channel/crypto-config/peerOrganizations/teco.com/users:/etc/hyperledger/msp/users
      - 'peer1.machine1.teco.com:/var/hyperledger/production'
    depends_on:
      - couchdb2
    networks:
      - basic
  ca.machine1.teco.com:
    image: 'vizlore/fabric-ca:latest'
    restart: always
    logging:
      options:
        max-size: 10m
    environment:
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.machine1.teco.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - >-
        FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.teco.com-cert.pem
      - >-
        FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a60c8a79b6fab763748093a995dd8e4f967ddfa4761143d280b4d120699edc53_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - '7054:7054'
    command: >-
      sh -c 'fabric-ca-server start --ca.certfile
      /etc/hyperledger/fabric-ca-server-config/ca.teco.com-cert.pem --ca.keyfile
      /etc/hyperledger/fabric-ca-server-config/a60c8a79b6fab763748093a995dd8e4f967ddfa4761143d280b4d120699edc53_sk
      -b admin:adminpw -d'
    volumes:
      - >-
        ./artifacts/channel/crypto-config/peerOrganizations/teco.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - './fabric-ca-server:/etc/hyperledger/fabric-ca-server'
    container_name: ca.machine1.teco.com
    networks:
      - basic
