Organizations:
 - &orderer
  Name: Orderer
  ID: OrdererMSP
  MSPDir: crypto-config/ordererOrganizations/teco.com/msp
  Policies:
   Readers:
    Type: Signature
    Rule: "OR('OrdererMSP.member')"
   Writers:
    Type: Signature
    Rule: "OR('OrdererMSP.member')"
   Admins:
    Type: Signature
    Rule: "OR('OrdererMSP.admin')"
 - &supp
  Name: supp
  ID: suppMSP
  MSPDir: crypto-config/peerOrganizations/teco.com/msp
  Policies:
   Readers:
    Type: Signature
    Rule: "OR('suppMSP.admin', 'suppMSP.peer', 'suppMSP.client')"
   Writers:
    Type: Signature
    Rule: "OR('suppMSP.admin', 'suppMSP.client')"
   Admins:
    Type: Signature
    Rule: "OR('suppMSP.admin')"
  

Capabilities:
 Channel: &ChannelCapabilities
  V1_4_2: true
 Orderer: &OrdererCapabilities
  V1_4_2: true
 Application: &ApplicationCapabilities
  V1_4_2: true
  V1_3: false
  V1_2: false
  V1_1: false

Application: &ApplicationDefaults
 Organizations:
 Policies:
  Readers:
   Type: ImplicitMeta
   Rule: "ANY Readers"
  Writers:
   Type: ImplicitMeta
   Rule: "ANY Writers"
  Admins:
   Type: ImplicitMeta
   Rule: "ANY Admins"
 Capabilities:
  <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
 OrdererType:  solo
 Addresses:
  - orderer0.teco.com:7050
 BatchTimeout: 1s
 BatchSize:
  MaxMessageCount: 10
  AbsoluteMaxBytes: 99 MB
  PreferredMaxBytes: 512 KB
 Policies:
  Readers:
   Type: ImplicitMeta
   Rule: "ANY Readers"
  Writers:
   Type: ImplicitMeta
   Rule: "ANY Writers"
  Admins:
   Type: ImplicitMeta
   Rule: "ANY Admins"
  BlockValidation:
   Type: ImplicitMeta
   Rule: "ANY Writers"
    
 Organizations:
 Policies:
  Readers:
   Type: ImplicitMeta
   Rule: "ANY Readers"
  Writers:
   Type: ImplicitMeta
   Rule: "ANY Writers"
  Admins:
   Type: ImplicitMeta
   Rule: "MAJORITY Admins"
  BlockValidation:
   Type: ImplicitMeta
   Rule: "ANY Writers"

Application: &ApplicationDefaults
 Organizations:
 Policies:
  Readers:
   Type: ImplicitMeta
   Rule: "ANY Readers"
  Writers:
   Type: ImplicitMeta
   Rule: "ANY Writers"
  Admins:
   Type: ImplicitMeta
   Rule: "ANY Admins"
  BlockValidation:
   Type: ImplicitMeta
   Rule: "ANY Writers"

Channel: &ChannelDefaults
 Policies:
  # Who may invoke the 'Deliver' API
  Readers:
   Type: ImplicitMeta
   Rule: "ANY Readers"
  # Who may invoke the 'Broadcast' API
  Writers:
   Type: ImplicitMeta
   Rule: "ANY Writers"
  # By default, who may modify elements at this config level
  Admins:
   Type: ImplicitMeta
   Rule: "ANY Admins"
 Capabilities:
  <<: *ChannelCapabilities

Profiles:
 ComposerOrdererGenesis:
  <<: *ChannelDefaults
  Orderer:
   <<: *OrdererDefaults
   Organizations:
    - *orderer
   Capabilities:
    <<: *OrdererCapabilities
  Consortiums:
   echannelConsortium:
    Organizations:
     - *supp
 echannel:
  Consortium: echannelConsortium
  <<: *ChannelDefaults
  Application:
   <<: *ApplicationDefaults
   Organizations:
     - *supp
  Capabilities:
   <<: *ApplicationCapabilities


